### ISSUE TITLE
Not clear how to assemble these components into a working app.

### ISSUE THREAD

**Issue by SteveOW** [sole/three.js-tutorials#1]
The 2 components (1 html and 1 javascript) do not seem sufficient to build the app described in the excellent tutorial which directed me here.
The referring tutorial describes an app where objects can be picked from a three.js graphics window inside a larger html page.
This issue is not about a bug. It reports a need for additional instructions.

**Comment by sole** [comment]
How to file a bug:
1. Describe what you did
2. Describe what you got
3. Describe what you expected to happen instead
4. BE NICE.

**Comment by sole** [comment]
As discussed in the email sent to @SteveOW

**Comment by sole** [comment]
You can learn about github, git and cloning in their help pages, which I heartily recommend if you want to use open source projects:
https://help.github.com/articles/set-up-git

Alternatively download the entire repo using this zip link:
https://github.com/sole/three.js-tutorials/archive/master.zip

Once you unpack it you'll get several folders with tutorials, open the object_picking one which is the one you want.

The version used in the tutorial page is modified so that I can keep stats on visitors.
